class_name GameConstants
extends RefCounted

const GAME_NAME: String = "Super Star Fighter"
const GAME_VERSION: String = "0.1.0-beta.15"
const RELEASE_LABEL: String = "BETA 15"
const ENGINE_VERSION: String = "4.7.2"
const PROTOCOL_VERSION: int = 45
const SHIELD_PRESS_RETENTION_TICKS: int = 15
const INPUT_STALE_SECONDS: float = 0.5

const DEFAULT_PORT: int = 7000
const MIN_PORT: int = 1024
const MAX_PORT: int = 65535

const DEFAULT_MAX_PLAYERS: int = 32
const MIN_PLAYERS: int = 2
const MAX_PLAYERS: int = 32

const DEFAULT_ROUNDS_TO_WIN: int = 3
const MIN_ROUNDS_TO_WIN: int = 1
const MAX_ROUNDS_TO_WIN: int = 5
const MATCH_EXTENSION_ROUNDS: int = 5

const PHYSICS_TICKS_PER_SECOND: int = 60
const INPUT_SEND_RATE: int = 30
const PLAYER_SNAPSHOT_RATE: int = 20
const PROJECTILE_CORRECTION_RATE: int = 5

const DRAFT_DURATION_SECONDS: float = 30.0
const COUNTDOWN_DURATION_SECONDS: float = 3.0
const HEAT_RESULT_DURATION_SECONDS: float = 2.0
const ROUND_RESULT_DURATION_SECONDS: float = 2.0
const HEAT_WINS_TO_WIN_ROUND: int = 2
const CARD_OFFER_SIZE: int = 5

const ARENA_SIZE: Vector2 = Vector2(3200.0, 1800.0)
const SHIP_COLLISION_RADIUS: float = 20.0
const PROJECTILE_RADIUS: float = 5.0
const PROJECTILE_LIFETIME_SECONDS: float = 2.5
const SHIELD_BLOCK_COST: float = 25.0
const REBOUND_SHIELD_RADIUS: float = 32.0
const REBOUND_SHIELD_DAMAGE_PER_SECOND: float = 20.0
const SHIELD_DEPLETION_THRESHOLD: float = 25.0
const SHIELD_ACCELERATION_FACTOR: float = 0.75
const PERFECT_GUARD_WINDOW_SECONDS: float = 0.25
const PERFECT_GUARD_BLOCK_COST_FACTOR: float = 0.2
const PERFECT_GUARD_FEEDBACK_SECONDS: float = 0.2
const KINETIC_VENT_MINIMUM_CHARGE: float = 25.0
const KINETIC_VENT_MAXIMUM_CHARGE: float = 100.0
const KINETIC_VENT_RADIUS: float = 240.0
const KINETIC_VENT_MINE_DISPLACEMENT_SECONDS: float = 0.4
const KINETIC_VENT_FEEDBACK_SECONDS: float = 0.3
const BREAKAWAY_DURATION_SECONDS: float = 0.85
const BREAKAWAY_COOLDOWN_SECONDS: float = 8.0
const BREAKAWAY_ACCELERATION_MULTIPLIER: float = 1.8
const BREAKAWAY_BRAKING_MULTIPLIER: float = 2.25
const BREAKAWAY_BURST_WINDOW_SECONDS: float = 0.35
const BREAKAWAY_BURST_HEALTH_FRACTION: float = 0.3
const MAX_PROJECTILES_PER_OWNER: int = 64
const MAX_PROJECTILES_GLOBAL: int = 1024
const DEAD_OWNER_PROJECTILE_LIFETIME: float = 0.5

const MINE_COOLDOWN_SECONDS: float = 3.0
const MINE_ACTIVATION_SECONDS: float = 0.25
const MINE_DAMAGE: float = 100.0
const MINE_RADIUS: float = 14.0
const MINE_TRIGGER_RADIUS: float = 70.0
const MINE_MAGNETIC_RADIUS: float = 320.0
const MINE_MAGNETIC_SPEED: float = 60.0
const MINE_MAGNETIC_TARGET_RATE: int = 10
const MINE_BLAST_RADIUS: float = 200.0

const MISSILE_COOLDOWN_SECONDS: float = 1.0
const MISSILE_DAMAGE: float = 40.0
const MISSILE_SPEED: float = 650.0
const MISSILE_RANGE: float = 1100.0
const MISSILE_RADIUS: float = 9.0
const MISSILE_ACQUISITION_HALF_ANGLE: float = deg_to_rad(35.0)
const MISSILE_GUIDANCE_HALF_ANGLE: float = deg_to_rad(70.0)
const MISSILE_TURN_RATE: float = deg_to_rad(90.0)

const CLOAK_DURATION_SECONDS: float = 5.0
const CLOAK_ATTACK_DELAY_SECONDS: float = 0.1
const CLOAK_COOLDOWN_SECONDS: float = 30.0
const CLOAK_DURATION_PER_EXTRA_CARD_SECONDS: float = 2.0
const CLOAK_COOLDOWN_PER_EXTRA_CARD: float = 0.5

const OVERTIME_START_SECONDS: float = 45.0
const OVERTIME_WARNING_SECONDS: float = 5.0
const OVERTIME_SHRINK_SECONDS: float = 45.0
const OVERTIME_TIME_LIMIT_SECONDS: float = 60.0
const OVERTIME_MINIMUM_RADIUS: float = 120.0
const OVERTIME_BASE_DAMAGE_PER_SECOND: float = 30.0
const OVERTIME_DAMAGE_STEP_SECONDS: float = 10.0
const OVERTIME_DAMAGE_STEP: float = 10.0
const OVERTIME_MAX_DAMAGE_PER_SECOND: float = 100.0
