extends RefCounted

const Policy = preload("res://src/client/presentation/competitive_view_policy.gd")


static func run(context: TestContext, parent: Node) -> void:
	var lobby := ServerLobby.new()
	lobby.admit(2, "Host")
	lobby.admit(3, "Guest")
	context.expect_false(lobby.config.competitive_view, "casual lobbies retain expanded view by default")
	lobby.request_ready(2, true)
	lobby.request_ready(3, true)
	context.expect_false(lobby.request_competitive_view(3, true).ok, "guests cannot change competitive visibility")
	context.expect_true(lobby.all_humans_ready(), "rejected view changes preserve readiness")
	context.expect_true(lobby.request_competitive_view(2, true).ok, "host can enable equal combat space")
	context.expect_false(lobby.all_humans_ready(), "view policy changes require players to ready again")
	context.expect_true(lobby.serialize().competitive_view, "lobby advertises view policy")
	context.expect_true(lobby.config.duplicate_config().competitive_view, "frozen match config preserves competitive policy")
	preload("res://src/shared/lobby/match_presets.gd").apply(lobby, 2, "duel")
	context.expect_true(lobby.config.competitive_view, "quick presets preserve explicit competitive policy")
	lobby.request_ready(2, true)
	lobby.request_ready(3, true)
	lobby.request_competitive_view(2, true)
	context.expect_true(lobby.all_humans_ready(), "idempotent policy requests do not clear readiness")
	lobby.request_start(2)
	context.expect_false(lobby.request_competitive_view(2, false).ok, "competitive policy is locked during a match")
	context.expect_false(lobby.request_competitive_view(ServerLobby.OPERATOR_AUTHORITY_ID, false).ok, "operators cannot change visibility midmatch")
	var world := AuthoritativeWorld.new()
	world.add_peer(2)
	world.add_peer(3)
	var coordinator := AuthoritativeMatchCoordinator.new(lobby, world, 42)
	coordinator.start(0)
	context.expect_true(coordinator.current_state_payload().competitive_view, "players and late spectators receive the frozen match view policy")
	context.expect_true(CommandLineConfig.parse(PackedStringArray(["--server", "--password=test-lobby", "--competitive-view"])).competitive_view, "dedicated startup supports competitive view")
	var window := parent.get_window()
	var previous := [window.content_scale_size, window.content_scale_mode, window.content_scale_aspect]
	var policy = Policy.new()
	policy.apply(window, true)
	context.expect_equal(window.content_scale_size, Vector2i(1920, 1080), "competitive world canvas uses reference size")
	context.expect_equal(policy.gameplay_point(Vector2(-500, 400)), Vector2(1, 400), "left black bar cannot hide the gameplay reticle")
	context.expect_equal(policy.gameplay_point(Vector2(2400, 1300)), Vector2(1919, 1079), "right and bottom black bars clamp the shared aim point")
	context.expect_equal(window.content_scale_aspect, Window.CONTENT_SCALE_ASPECT_KEEP, "native renderer constrains both wider and taller displays")
	policy.apply(window, true)
	policy.restore()
	context.expect_equal(policy.gameplay_point(Vector2(-500, 400)), Vector2(-500, 400), "casual input remains unrestricted")
	context.expect_equal([window.content_scale_size, window.content_scale_mode, window.content_scale_aspect], previous, "repeated activation restores exact original window policy")
	for size in [Vector2(1280, 720), Vector2(1920, 1080), Vector2(2560, 1080), Vector2(2880, 1920), Vector2(3440, 1440), Vector2(5120, 1440)]:
		var fitted: Rect2 = Policy.physical_content_rect(size)
		context.expect_true(is_equal_approx(fitted.size.x / fitted.size.y, 16.0 / 9.0), "combat content retains aspect at %s" % size)
		context.expect_equal(fitted.get_center(), size * 0.5, "combat content stays centered at %s" % size)
	var view := NetworkWorldFixture.new()
	parent.add_child(view)
	view.set_network_active(true)
	view.apply_match_state({"state_name": "ACTIVE_HEAT", "competitive_view": true})
	context.expect_true(view.hud_camera.competitive_view_policy.active, "network match activates constrained canvas")
	view.set_network_active(false)
	context.expect_equal([window.content_scale_size, window.content_scale_mode, window.content_scale_aspect], previous, "disconnect restores menu canvas")
	view.set_network_active(true)
	view.apply_match_state({"state_name": "DRAFT", "competitive_view": true})
	view.free()
	context.expect_equal([window.content_scale_size, window.content_scale_mode, window.content_scale_aspect], previous, "exiting client tree restores original viewport")
