extends RefCounted

const Preferences = preload("res://src/client/ui/connection_preferences.gd")


static func run(context: TestContext) -> void:
	var path := "res://.tools/connection-preferences-%d.cfg" % Time.get_ticks_usec()
	var initial := ConfigFile.new()
	initial.set_value("audio", "master", 0.42)
	initial.set_value("appearance", "ship_color", "invalid")
	initial.set_value("appearance", "ship_pattern", "invalid")
	initial.save(path)
	var preferences := Preferences.new(path)
	context.expect_equal(preferences.load_appearance(), OK, "appearance loads independently of UI lifecycle")
	context.expect_equal(preferences.ship_color, Color("42e8ff"), "invalid stored color retains the default")
	context.expect_equal(preferences.ship_pattern, &"solid", "invalid stored pattern retains the default")
	context.expect_equal(preferences.save_appearance(false, Color("abcdef"), &"solid"), OK, "appearance writes succeed")
	var reopened := Preferences.new(path)
	reopened.load_appearance()
	context.expect_equal(reopened.ship_color, Color("abcdef"), "appearance survives a new preferences instance")
	context.expect_false(reopened.random_color, "random appearance preference survives reload")
	preferences.begin_attempt(" EXAMPLE.COM ", 7000, "first-password", true)
	context.expect_equal(preferences.password_for_endpoint("example.com", 7000), "", "unconfirmed admission never persists credentials")
	preferences.confirm_connected()
	context.expect_equal(reopened.password_for_endpoint("example.com", 7000), "first-password", "successful admission commits to the normalized endpoint")
	context.expect_equal(reopened.password_for_endpoint("example.com", 7001), "", "passwords remain isolated by port")
	preferences.begin_attempt("example.com", 7000, "failed-password", true)
	preferences.discard_attempt()
	preferences.confirm_connected()
	context.expect_equal(reopened.password_for_endpoint("example.com", 7000), "first-password", "cancelled admission cannot overwrite stored credentials")
	preferences.begin_attempt("example.com", 7000, "first-password", false)
	preferences.confirm_connected()
	context.expect_equal(reopened.password_for_endpoint("example.com", 7000), "", "unchecking remember removes credentials after admission")
	initial.load(path)
	context.expect_equal(initial.get_value("audio", "master"), 0.42, "preference updates preserve other settings sections")
	context.expect_equal(Preferences.endpoint_key("[2001:db8::1]", 7000), Preferences.endpoint_key("2001:db8::1", 7000), "IPv6 bracket normalization preserves existing keys")
	context.expect_equal(Preferences.endpoint_key("", 7000), "", "empty endpoint is not persisted")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
